version: '3.5'

services:
  db:
    image: postgres:14.5
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=red_mad_robot
      - TZ=Asia/Almaty
